service: fulfillment
provider:
  name: aws
  runtime: nodejs6.10
package:
  individually: true

functions:
  getFulfilmentData:
    handler: handler.get
    events:
      - http:
          path: /
          method: get
  postFulfilmentData:
    handler: handler.post
    events:
      - http:
          path: /
          method: post
